name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Environment (Node 12.x)
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 12.x
          check-latest: true
      - name: Dependencies
        run: npx yarn install --frozen-lockfile
      - name: Tests
        run: yarn test
